# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lb2', '0003_auto_20171015_2006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proportion',
            unique_together=set([('height', 'sex')]),
        ),
    ]
