# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb2', '0005_auto_20171015_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lb2.Docror'),
        ),
    ]
