# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lb2', '0006_auto_20171015_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docror',
            name='work_place',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='head',
        ),
        migrations.DeleteModel(
            name='Docror',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
